package com.csms.computer_store.Repository;

import com.csms.computer_store.Entity.SystemPerformanceReport;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;

@Repository
public interface SystemPerformanceReportRepository extends JpaRepository<SystemPerformanceReport, Long> {

    // Find reports within a date range
    List<SystemPerformanceReport> findByStartDateGreaterThanEqualAndEndDateLessThanEqual(
            LocalDate startDate, LocalDate endDate);

    // Find reports generated by a specific technician
    List<SystemPerformanceReport> findByGeneratedBy(String generatedBy);

    // Find reports with high CPU usage
    List<SystemPerformanceReport> findByCpuUsageGreaterThan(double threshold);

    // Find reports with many errors
    List<SystemPerformanceReport> findByErrorCountGreaterThan(int minErrors);
}
